FROM ocamlpro/ocaml:@OCaml_Compiler_Version@ as ae-compilation

LABEL maintainer="elias.bendjaballah@gmail.com"
LABEL description="Light docker images for the SMT solver alt-ergo (no handling of the GUI is proposed for `slim` images) "

RUN opam switch create . ocaml-system --deps --locked && \
    eval `opam env` && \
    opam update &&\
    eval `opam env` && \
    opam install -y @Opam_deps@ alt-ergo.@AE_TAG_VERSION@ && \
    sudo cp /home/ocaml/_opam/bin/alt-ergo /usr/local/bin/alt-ergo-@AE_TAG_VERSION@ && \
    rm -rf _opam && \
    rm -rf .opam

WORKDIR /home/ocaml
RUN rm -rf /home/ocaml/alt-ergo

FROM alpine:@Alpine_Output_Version@ as target

RUN apk add @Target_Pkgs@

RUN addgroup -S iamproof && adduser -S iamproof -G iamproof -s /bin/sh
RUN echo 'iamproof ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
USER iamproof
WORKDIR /home/ocaml

COPY --from=ae-compilation /usr/local/bin/alt-ergo-@AE_TAG_VERSION@ /usr/local/bin/
